// Generated by BootstrapCompiler v2 (Misha .mih/.mixa -> Java) - покрывает 20 разделов
// Source: Misha spec 1-20
// all_features.mix - демо проект на .mix с ВСЕМИ фишками языка Misha (.mixa) 20 разделов
// Сборка: java -cp mvm/target compiler.BootstrapCompiler examples/all_features.mix -o examples/all_features.mvm
// Запуск: java -cp mvm/target mvm.MVM examples/all_features.mvm
// Также: java -cp mvm/target compiler.BootstrapCompiler examples/all_features.mix -o examples/all_features.java -target java
package com.misha.demo

import java.util.List
import misha.Runtime

// 1. модификаторы + 2. классы
public class Demo extends Object implements Runnable {
    private String name = "Misha"
    protected int age = 17
    static final VER = "1.0"
    abstract class Inner { abstract int area() }
}

// 2. interface
interface Animal { public void sound() }

// 8. аннотации (все группы)
@Override
@Data
@Singleton
@Fast
@Cache
@XOR
@BASE64
@O3
@Inline
public class AllDemo {
    // 4. методы
    public int calc(int a, int b) { return a + b }
    public void hello() { System.out.println("hi " + (name) + "") }

    public void runAll() {
        // 3. переменные авто + явные
        var s1 = "lol"
        var i1 = 10
        var f1 = 10.5
        var big = 10.5d
        var String exp = "test"
        String s = "hi"
        float f = 10.5
        double d = 10.5d
        char c = 'A'
        boolean flag = true
        long bigNum = 100L
        final MAX = 100
        System.out.println("vars " + (s1) + " " + (i1) + " " + (exp) + "")

        // 5. условные
        var age = 20
        if age > 18 { System.out.println("adult") }
        if age > 18 { System.out.println("adult2") } else { System.out.println("kid") }
        if age < 13 { System.out.println("kid") } else if age < 18 { System.out.println("teen") } else { System.out.println("adult") }
        if (age > 18) System.out.println("OK");
        var st = age > 18 ? "yes" : "no"
        System.out.println("ternary " + (st) + "")

        // 6. циклы
        for (var i = 0; i < 3; i++) { System.out.println("for " + (i) + "") }
        for item : [10,20,30] { System.out.println("each " + (item) + "") }
        var w = 2
        while w > 0 { System.out.println("while " + (w) + "") w = w - 1 }
        do { System.out.println("do") } while false

        // 7. print + строки
        var txt = " Hello "
        System.out.println("hi " + (s1) + "")
        System.out.println(txt.toLowerCase())
        System.out.println(txt.toUpperCase())
        System.out.println(txt.trim())
        System.out.println(txt.replace("l","L"))
        System.out.println(txt.contains("ell"))
        System.out.println(txt.split(" "))
        System.out.println("a\nb\tc \"q\" C:\\path")

        // 9. массивы/коллекции
        var nums = new Object[]{1,2,3,4,5}
        System.out.println("nums len " + (misha.Runtime.len(nums)) + "")
        var lst = new java.util.ArrayList<>()
        lst.add("x")
        var mp = new java.util.HashMap<>()
        mp.put("k","v")
        var st2 = new java.util.HashSet<>()
        st2.add(1)

        // 10. встроенные математика/строки/массивы/логика/случайные
        System.out.println("sum " + (misha.Runtime.sum(5,3)) + "")
        System.out.println("pow " + (misha.Runtime.pow(2,3)) + "")
        System.out.println("sqrt " + (misha.Runtime.sqrt(16)) + "")
        System.out.println("abs " + (misha.Runtime.abs(-5)) + "")
        System.out.println("min " + (misha.Runtime.min(5,3)) + "")
        System.out.println("max " + (misha.Runtime.max(5,3)) + "")
        System.out.println("len " + (misha.Runtime.len([1,2,3])) + "")
        System.out.println("first " + (misha.Runtime.first([1,2,3])) + "")
        System.out.println("rand " + (misha.Runtime.randint(10)) + "")
        System.out.println("choice " + (misha.Runtime.choice([1,2,3])) + "")

        // 11. исключения
        try { var x = 10 / 0 } catch (Exception e) { System.out.println("catch " + (e) + "") } finally { System.out.println("finally") }
        try { System.out.println("t2") } catch (Exception e) { System.out.println("e2 " + (e) + "") }

        // 12. дженерики
        var box = Box<String>()
        box.set("hi")
        System.out.println("box " + (box.get()) + "")

        // 14. лямбды
        var fn = (a, b) -> a + b
        System.out.println("fn " + (fn) + "")

        // 17. память
        var mem = misha.Runtime.alloc(10)
        System.out.println("alloc " + (mem) + "")
        misha.Runtime.free(mem)
        misha.Runtime.gc()
        System.out.println(meminfo())

        misha.Runtime.sleep(5)
        System.out.println("done .mix")
    }
}

// 12. дженерик отдельно
public class Box<T> { var content public void set(T v){ content=v } public T get(){ return content } }

// 13. enum
enum Color { RED, GREEN, BLUE }

// 16. шифрование распределенный ключ
@Part
public class Part1 { var a = "mod" }
@Mosn
public class Part2 { var b = "secret" }
