// Generated by BootstrapCompiler v2 (Misha .mih/.mixa -> Java) - покрывает 20 разделов
// Source: Misha spec 1-20
// full.mih - полный тест всех 20 разделов спеки Misha (.mih)
package com.misha.demo

import java.util.List
import misha.Runtime

// 2. классы и 1. модификаторы
public class MyClass extends Parent implements Runnable {
    private String name
    static final MAX = 100
}

// 8. аннотации
@Override
@Data
@Singleton
@Fast
public class Demo {
    // 4. методы
    public int calculate(int a, int b) {
        return a + b
    }
    public void showMessage() {
        System.out.println("Привет из " + (name) + "")
    }
    // 3. переменные и типы
    var autoStr = "lol"
    var autoInt = 10
    var autoFloat = 10.5
    var String explicit = "test"
    String s = "hi"
    float f = 10.5
    final NAME = "misha"

    public void testAll() {
        // 5. условные
        var age = 20
        if age > 18 {
            System.out.println("Взрослый")
        }
        if age > 18 {
            System.out.println("Взрослый")
        } else {
            System.out.println("Ребёнок")
        }
        if age < 13 {
            System.out.println("Ребёнок")
        } else if age < 18 {
            System.out.println("Подросток")
        } else {
            System.out.println("Взрослый")
        }
        if (age > 18) System.out.println("ОК");
        var status = age > 18 ? "взрослый" : "ребёнок"
        System.out.println("status=" + (status) + "")

        // 6. циклы
        for (var i = 0; i < 3; i++) {
            System.out.println("for i=" + (i) + "")
        }
        for item : [1,2,3] {
            System.out.println("item=" + (item) + "")
        }
        var w = 3
        while w > 0 {
            System.out.println("while " + (w) + "")
            w = w - 1
        }
        do {
            System.out.println("do-while")
        } while false

        // 7. вывод + методы строк
        var text = " hello "
        System.out.println("Привет " + (name) + "")
        System.out.println(text.toLowerCase())
        System.out.println(text.toUpperCase())
        System.out.println(text.trim())
        System.out.println(text.replace("l","L"))

        // 9. массивы/коллекции
        var numbers = new Object[]{1, 2, 3, 4, 5}
        var names = new Object[]{"Анна", "Иван"}
        System.out.println(numbers[0])
        var lenNums = misha.Runtime.len(numbers)
        System.out.println("len=" + (lenNums) + "")
        var list = new java.util.ArrayList<>()
        list.add("элемент")
        var map = {"name": "Иван", "age": 25}
        var set = new java.util.HashSet<>()
        set.add(1)

        // 10. встроенные
        System.out.println("sum=" + (misha.Runtime.sum(5,3)) + "")
        System.out.println("pow=" + (misha.Runtime.pow(2,3)) + "")
        System.out.println("sqrt=" + (misha.Runtime.sqrt(16)) + "")
        System.out.println("min=" + (misha.Runtime.min(5,3)) + "")
        System.out.println("rand=" + (misha.Runtime.randint(10)) + "")

        // 11. исключения
        try {
            var x = 10 / 0
        } catch (Exception e) {
            System.out.println("Ошибка: " + (e) + "")
        } finally {
            System.out.println("finally")
        }
        try {
            System.out.println("try2")
        } catch (Exception e) {
            System.out.println("catch e=" + (e) + "")
        }

        // 12. дженерики
        var box = Box<String>()
        box.set("Привет")

        // 13. enum
        // 14. лямбды
        var sumFn = (a, b) -> a + b
        System.out.println("lambda sum=" + (sumFn) + "")

        // 17. память
        var obj = misha.Runtime.alloc(100)
        System.out.println("alloc " + (obj) + "")
        misha.Runtime.free(obj)
        misha.Runtime.gc()
        System.out.println(meminfo())

        // 10 random
        System.out.println("choice=" + (misha.Runtime.choice([1,2,3])) + "")

        misha.Runtime.sleep(10)
        System.out.println("done")
    }
}

// 13. enum отдельно
enum Color {
    RED, GREEN, BLUE
}

// 12. дженерик класс
public class Box<T> {
    var content
    public void set(T item) {
        content = item
    }
    public T get() {
        return content
    }
}

// 18. шифрование + 16
@XOR
@BASE64
public class SecureData {
    @Part
    var code = "secret"
}

// 19. флаги
@O3
@Inline
public void fastMethod() {
    System.out.println("fast")
}
