// Generated by BootstrapCompiler v2 (Misha .mih/.mixa -> Java) - покрывает 20 разделов
// Source: Misha spec 1-20
public class Test {
    var name = "miha"
    public static void testprint() {
        System.out.println(name)
    }
}
