// Generated by BootstrapCompiler v2 (Misha .mih/.mixa -> Java) - покрывает 20 разделов
// Source: Misha spec 1-20
// test lambda без ->
var getChoice = () -> { return misha.Runtime.choice([1,2,3]) }
var sum = (a,b) -> { return a + b }

var x = getChoice()
System.out.println("getChoice()=" + (x) + "")

var y = misha.Runtime.sum(5,3)
System.out.println("misha.Runtime.sum(5,3)=" + (y) + "")

// старый var fn -> остается
var fn = (a, b) -> a + b
System.out.println("fn via var still works")
System.out.println("done lambda test")
